version: '2'
services:
  nse-portal:
    restart: always
    build: .
    container_name: nse
    ports:
     - "3000:3000"
    env_file:
     - /opt/nse/etc/envVars
    volumes:
     - /opt/nse/log:/home/mean/logs
     - /opt/nse/docs:/home/mean/docs
     - /opt/nse/reports:/home/mean/reports
    networks:
     - nse-private

networks:
 nse-private:
  external: true
